
import mongoose from 'mongoose';

// --- Generate ObjectIDs to link documents ---
const schoolIds = Array.from({ length: 25 }, () => new mongoose.Types.ObjectId());

// --- Schools Data ---
export const schools = [
  // Maharashtra Schools (Mumbai, Pune, Nagpur)
  {
    _id: schoolIds[0],
    name: "Dhirubhai Ambani International School",
    description: "A leading international school in Mumbai offering a world-class education.",
    board: "IB",
    state: "Maharashtra",
    city: "Mumbai",
    schoolMode: "private",
    genderType: "co-ed",
    shifts: ["morning"],
    feeRange: "More than 5 Lakh",
    rank: "1",
    address: "Bandra-Kurla Complex, Bandra (East)",
    pinCode: 400098,
    upto: "Grade 12",
    email: "info.dais@school.com",
    mobileNo: "9876543210",
    specialist: ["IB Curriculum", "Cultural Education"],
    tags: ["international", "premium", "top-rated"],
    website: "https://www.dais.edu.in",
    status: "accepted",
    languageMedium: ["English"],
    transportAvailable: "yes",
  },
  {
    _id: schoolIds[1],
    name: "Podar International School",
    description: "Part of the Podar Education Network, focusing on traditional values and modern teaching.",
    board: "CBSE",
    state: "Maharashtra",
    city: "Mumbai",
    schoolMode: "private",
    genderType: "co-ed",
    shifts: ["morning", "afternoon"],
    feeRange: "1 Lakh - 2 Lakh",
    rank: "15",
    address: "Santacruz West",
    pinCode: 400054,
    upto: "Grade 12",
    email: "info.podar@school.com",
    mobileNo: "9876543211",
    specialist: ["Technology Integration", "Holistic Development"],
    tags: ["cbse", "tech-savvy"],
    website: "https://www.podareducation.org",
    status: "accepted",
    languageMedium: ["English"],
    transportAvailable: "yes",
  },
  {
    _id: schoolIds[2],
    name: "St. Xavier's High School",
    description: "A well-respected institution known for its strong academic foundation and .",
    board: "SSC",
    state: "Maharashtra",
    city: "Mumbai",
    schoolMode: "convent",
    genderType: "boy",
    shifts: ["morning"],
    feeRange: "50000 - 75000",
    address: "Fort, Mumbai",
    pinCode: 400001,
    upto: "Grade 10",
    email: "info.xaviers@school.com",
    mobileNo: "9876543212",
    tags: ["legacy", "academics"],
    status: "accepted",
    languageMedium: ["English"],
    transportAvailable: "no",
  },
  {
    _id: schoolIds[3],
    name: "The Bishop's School",
    description: "One of Pune's oldest and most prestigious schools with a rich history.",
    board: "ICSE",
    state: "Maharashtra",
    city: "Pune",
    schoolMode: "private",
    genderType: "boy",
    shifts: ["morning"],
    feeRange: "75000 - 100000",
    rank: "5",
    address: "Camp, Pune",
    pinCode: 411001,
    upto: "Grade 12",
    email: "info.bishops@school.com",
    mobileNo: "9876543213",
    specialist: ["Sports Excellence", "Leadership Development"],
    tags: ["icse", "sports", "pune"],
    website: "https://www.thebishopsschool.org",
    status: "accepted",
    languageMedium: ["English"],
    transportAvailable: "yes",
  },
  {
    _id: schoolIds[4],
    name: "Symbiosis International School",
    description: "Offers a blend of international curricula to foster global citizens.",
    board: "IB",
    state: "Maharashtra",
    city: "Pune",
    schoolMode: "private",
    genderType: "co-ed",
    shifts: ["morning"],
    feeRange: "3 Lakh - 4 Lakh",
    address: "Viman Nagar, Pune",
    pinCode: 411014,
    upto: "Grade 12",
    email: "info.symbiosis@school.com",
    mobileNo: "9876543214",
    specialist: ["Inquiry-based Learning", "Cultural Education"],
    tags: ["ib", "international", "pune"],
    website: "https://www.sis.ac.in",
    status: "accepted",
    languageMedium: ["English"],
    transportAvailable: "yes",
  },
  {
    _id: schoolIds[5],
    name: "Pune Zilla Parishad School",
    description: "A government school providing accessible education to all sections of society.",
    board: "MSBSHSE",
    state: "Maharashtra",
    city: "Pune",
    schoolMode: "government",
    genderType: "co-ed",
    shifts: ["morning", "afternoon"],
    feeRange: "1000 - 10000",
    address: "Hadapsar, Pune",
    pinCode: 411028,
    upto: "Grade 10",
    email: "info.pzp@school.gov.in",
    mobileNo: "9876543215",
    tags: ["government", "affordable", "marathi-medium"],
    status: "accepted",
    languageMedium: ["Marathi", "English"],
    transportAvailable: "no",
  },
  {
    _id: schoolIds[6],
    name: "Centre Point School",
    description: "A top-rated CBSE school in Nagpur known for excellent results and infrastructure.",
    board: "CBSE",
    state: "Maharashtra",
    city: "Nagpur",
    schoolMode: "private",
    genderType: "co-ed",
    shifts: ["morning"],
    feeRange: "1 Lakh - 2 Lakh",
    rank: "1",
    address: "Katol Road, Nagpur",
    pinCode: 440013,
    upto: "Grade 12",
    email: "info.cps@school.com",
    mobileNo: "9876543216",
    specialist: ["STEM Activities", "Competitive Exam Prep"],
    tags: ["cbse", "nagpur", "results"],
    website: "https://www.centrepointschools.com",
    status: "accepted",
    languageMedium: ["English"],
    transportAvailable: "yes",
  },
  {
    _id: schoolIds[7],
    name: "Modern School",
    description: "Focuses on holistic education with a balance between academics and extra-curriculars.",
    board: "SSC",
    state: "Maharashtra",
    city: "Nagpur",
    schoolMode: "private",
    genderType: "co-ed",
    shifts: ["morning"],
    feeRange: "50000 - 75000",
    address: "Koradi Road, Nagpur",
    pinCode: 440026,
    upto: "Grade 12",
    email: "info.modern@school.com",
    mobileNo: "9876543217",
    tags: ["ssc", "nagpur", "holistic"],
    status: "accepted",
    languageMedium: ["English", "Marathi"],
    transportAvailable: "yes",
  },
  // Karnataka Schools (Bengaluru, Mysuru, Mangalore)
  {
    _id: schoolIds[8],
    name: "Indus International School",
    description: "A premier international boarding school in Bengaluru with a focus on leadership.",
    board: "IB",
    state: "Karnataka",
    city: "Bengaluru",
    schoolMode: "private",
    genderType: "co-ed",
    shifts: ["morning"],
    feeRange: "More than 5 Lakh",
    rank: "1",
    address: "Sarjapur, Bengaluru",
    pinCode: 562125,
    upto: "Grade 12",
    email: "info.indus@school.com",
    mobileNo: "9988776650",
    specialist: ["Leadership Development", "Community Service"],
    tags: ["ib", "boarding", "premium"],
    website: "https://www.indusschool.com",
    status: "accepted",
    languageMedium: ["English"],
    transportAvailable: "yes",
  },
  {
    _id: schoolIds[9],
    name: "National Public School, Indiranagar",
    description: "Highly sought-after school known for its exceptional academic record.",
    board: "CBSE",
    state: "Karnataka",
    city: "Bengaluru",
    schoolMode: "private",
    genderType: "co-ed",
    shifts: ["morning"],
    feeRange: "2 Lakh - 3 Lakh",
    rank: "3",
    address: "Indiranagar, Bengaluru",
    pinCode: 560038,
    upto: "Grade 12",
    email: "info.nps@school.com",
    mobileNo: "9988776651",
    specialist: ["Focusing on Academics", "Special Focus on Science"],
    tags: ["cbse", "academics", "bengaluru"],
    website: "https://www.npsinr.com",
    status: "accepted",
    languageMedium: ["English"],
    transportAvailable: "no",
  },
  {
    _id: schoolIds[10],
    name: "Bishop Cotton Boy's School",
    description: "A historic all-boys school with a strong legacy in sports and academics.",
    board: "ICSE",
    state: "Karnataka",
    city: "Bengaluru",
    schoolMode: "private",
    genderType: "boy",
    shifts: ["morning"],
    feeRange: "1 Lakh - 2 Lakh",
    address: "Residency Road, Bengaluru",
    pinCode: 560025,
    upto: "Grade 12",
    email: "info.bcbs@school.com",
    mobileNo: "9988776652",
    specialist: ["Empowering in Sports"],
    tags: ["icse", "legacy", "boys-school"],
    status: "accepted",
    languageMedium: ["English"],
    transportAvailable: "yes",
  },
  {
    _id: schoolIds[11],
    name: "Kendriya Vidyalaya, Malleswaram",
    description: "A central government school providing quality education at an affordable cost.",
    board: "KVS",
    state: "Karnataka",
    city: "Bengaluru",
    schoolMode: "government",
    genderType: "co-ed",
    shifts: ["morning"],
    feeRange: "10000 - 25000",
    address: "Malleswaram, Bengaluru",
    pinCode: 560003,
    upto: "Grade 12",
    email: "info.kv@school.gov.in",
    mobileNo: "9988776653",
    tags: ["kvs", "government", "affordable"],
    status: "accepted",
    languageMedium: ["English", "Hindi"],
    transportAvailable: "no",
  },
  {
    _id: schoolIds[12],
    name: "JSS Public School",
    description: "A well-regarded school in Mysuru promoting holistic development and cultural values.",
    board: "CBSE",
    state: "Karnataka",
    city: "Mysuru",
    schoolMode: "private",
    genderType: "co-ed",
    shifts: ["morning"],
    feeRange: "50000 - 75000",
    address: "J.P. Nagar, Mysuru",
    pinCode: 570008,
    upto: "Grade 12",
    email: "info.jss@school.com",
    mobileNo: "9988776654",
    specialist: ["Cultural Education", "Environmental Awareness"],
    tags: ["cbse", "mysuru", "values"],
    website: "https://www.jsspublicschool.com",
    status: "accepted",
    languageMedium: ["English"],
    transportAvailable: "yes",
  },
  {
    _id: schoolIds[13],
    name: "Karnataka State Board High School",
    description: "A state-run school offering education based on the Karnataka state curriculum.",
    board: "KSEEB",
    state: "Karnataka",
    city: "Mysuru",
    schoolMode: "government",
    genderType: "co-ed",
    shifts: ["morning", "afternoon"],
    feeRange: "1000 - 10000",
    address: "Saraswathipuram, Mysuru",
    pinCode: 570009,
    upto: "Grade 10",
    email: "info.kseeb@school.gov.in",
    mobileNo: "9988776655",
    tags: ["kseeb", "state-board", "kannada-medium"],
    status: "accepted",
    languageMedium: ["Kannada", "English"],
    transportAvailable: "no",
  },
  {
    _id: schoolIds[14],
    name: "St. Aloysius College Higher Primary School",
    description: "A renowned institution in Mangalore with a history of academic excellence.",
    board: "STATE",
    state: "Karnataka",
    city: "Mangalore",
    schoolMode: "convent",
    genderType: "co-ed",
    shifts: ["morning"],
    feeRange: "25000 - 50000",
    address: "Light House Hill Road, Mangalore",
    pinCode: 575003,
    upto: "Grade 10",
    email: "info.sac@school.com",
    mobileNo: "9988776656",
    tags: ["state", "mangalore", "convent"],
    status: "pending",
    languageMedium: ["English"],
    transportAvailable: "yes",
  },
  // Additional mixed data to ensure filter results
  {
    _id: schoolIds[15],
    name: "Ryan International School",
    description: "Focuses on all-round development with a balanced approach to academics and arts.",
    board: "IGCSE",
    state: "Maharashtra",
    city: "Mumbai",
    schoolMode: "private",
    genderType: "co-ed",
    shifts: ["morning"],
    feeRange: "2 Lakh - 3 Lakh",
    address: "Chembur, Mumbai",
    pinCode: 400071,
    upto: "Grade 12",
    email: "info.ryan.chembur@school.com",
    mobileNo: "9123456780",
    specialist: ["Empowering in Arts", "Global Curriculum"],
    tags: ["igcse", "arts", "mumbai"],
    status: "accepted",
    languageMedium: ["English"],
    transportAvailable: "yes",
  },
  {
    _id: schoolIds[16],
    name: "Delhi Public School, Pune",
    description: "A branch of the prestigious DPS society, offering quality CBSE education.",
    board: "CBSE",
    state: "Maharashtra",
    city: "Pune",
    schoolMode: "private",
    genderType: "co-ed",
    shifts: ["morning"],
    feeRange: "1 Lakh - 2 Lakh",
    rank: "8",
    address: "Mohammadwadi, Pune",
    pinCode: 411060,
    upto: "Grade 12",
    email: "info.dpspune@school.com",
    mobileNo: "9123456781",
    tags: ["dps", "cbse", "pune"],
    website: "https://www.dpspune.com",
    status: "accepted",
    languageMedium: ["English"],
    transportAvailable: "yes",
  },
  {
    _id: schoolIds[17],
    name: "Jawahar Navodaya Vidyalaya, Nagpur",
    description: "A central government school for talented students, primarily from rural areas.",
    board: "JNV",
    state: "Maharashtra",
    city: "Nagpur",
    schoolMode: "government",
    genderType: "co-ed",
    shifts: ["morning"],
    feeRange: "1000 - 10000",
    address: "Dhatav, Nagpur",
    pinCode: 441104,
    upto: "Grade 12",
    email: "info.jnvnagpur@school.gov.in",
    mobileNo: "9123456782",
    tags: ["jnv", "boarding", "rural-talent"],
    status: "accepted",
    languageMedium: ["English", "Hindi"],
    transportAvailable: "yes",
  },
  {
    _id: schoolIds[18],
    name: "The Valley School",
    description: "A school based on the teachings of J. Krishnamurti, fostering a unique learning environment.",
    board: "CISCE",
    state: "Karnataka",
    city: "Bengaluru",
    schoolMode: "private",
    genderType: "co-ed",
    shifts: ["morning"],
    feeRange: "4 Lakh - 5 Lakh",
    address: "Kanakapura Road, Bengaluru",
    pinCode: 560082,
    upto: "Grade 12",
    email: "info.valley@school.com",
    mobileNo: "9123456783",
    specialist: ["Environmental Awareness", "Holistic Philosophy"],
    tags: ["cisce", "alternative-education", "nature"],
    status: "accepted",
    languageMedium: ["English"],
    transportAvailable: "yes",
  },
  {
    _id: schoolIds[19],
    name: "Sharada Vidyaniketana Public School",
    description: "A school in Mangalore dedicated to providing value-based education.",
    board: "CBSE",
    state: "Karnataka",
    city: "Mangalore",
    schoolMode: "private",
    genderType: "co-ed",
    shifts: ["morning"],
    feeRange: "75000 - 100000",
    address: "Talapady, Mangalore",
    pinCode: 575022,
    upto: "Grade 12",
    email: "info.sharada@school.com",
    mobileNo: "9123456784",
    tags: ["cbse", "mangalore", "values"],
    status: "rejected",
    languageMedium: ["English"],
    transportAvailable: "yes",
  },
  {
    _id: schoolIds[20],
    name: "Hiranandani Foundation School",
    description: "Located in the Hiranandani Estate, offering ICSE curriculum.",
    board: "ICSE",
    state: "Maharashtra",
    city: "Mumbai",
    schoolMode: "private",
    genderType: "co-ed",
    shifts: ["morning", "afternoon"],
    feeRange: "1 Lakh - 2 Lakh",
    address: "Powai, Mumbai",
    pinCode: 400076,
    upto: "Grade 12",
    email: "info.hfs@school.com",
    mobileNo: "9123456785",
    tags: ["icse", "powai", "mumbai"],
    status: "accepted",
    languageMedium: ["English"],
    transportAvailable: "no",
  },
  {
    _id: schoolIds[21],
    name: "Vibgyor High School",
    description: "Known for its student-centric approach and modern infrastructure.",
    board: "CISCE",
    state: "Maharashtra",
    city: "Pune",
    schoolMode: "private",
    genderType: "co-ed",
    shifts: ["morning"],
    feeRange: "2 Lakh - 3 Lakh",
    address: "Balewadi, Pune",
    pinCode: 411045,
    upto: "Grade 12",
    email: "info.vibgyorpune@school.com",
    mobileNo: "9123456786",
    specialist: ["Focuses on Practical Learning", "Empowering in Sports"],
    tags: ["cisce", "sports", "pune"],
    status: "accepted",
    languageMedium: ["English"],
    transportAvailable: "yes",
  },
  {
    _id: schoolIds[22],
    name: "Greenwood High International School",
    description: "Top-tier international school with multiple curricula options.",
    board: "IGCSE",
    state: "Karnataka",
    city: "Bengaluru",
    schoolMode: "private",
    genderType: "co-ed",
    shifts: ["morning"],
    feeRange: "4 Lakh - 5 Lakh",
    address: "Sarjapur Road, Bengaluru",
    pinCode: 560087,
    upto: "Grade 12",
    email: "info.greenwood@school.com",
    mobileNo: "9123456787",
    specialist: ["Technology Integration", "Cultural Education"],
    tags: ["igcse", "ib", "premium"],
    status: "accepted",
    languageMedium: ["English"],
    transportAvailable: "yes",
  },
  {
    _id: schoolIds[23],
    name: "Night High School, Dadar",
    description: "Provides educational opportunities for working students.",
    board: "SSC",
    state: "Maharashtra",
    city: "Mumbai",
    schoolMode: "private",
    genderType: "co-ed",
    shifts: ["night school"],
    feeRange: "10000 - 25000",
    address: "Dadar, Mumbai",
    pinCode: 400028,
    upto: "Grade 10",
    email: "info.nighschool@school.com",
    mobileNo: "9123456788",
    tags: ["night-school", "ssc", "mumbai"],
    status: "pending",
    languageMedium: ["Marathi", "Hindi"],
    transportAvailable: "no",
  },
  {
    _id: schoolIds[24],
    name: "Mysuru Public School",
    description: "A community-focused school with a strong emphasis on local culture and academics.",
    board: "KSEEB",
    state: "Karnataka",
    city: "Mysuru",
    schoolMode: "private",
    genderType: "co-ed",
    shifts: ["morning"],
    feeRange: "25000 - 50000",
    address: "Kuvempunagar, Mysuru",
    pinCode: 570023,
    upto: "Grade 10",
    email: "info.mysurupublic@school.com",
    mobileNo: "9123456789",
    specialist: ["Cultural Education", "Special Focus on Mathematics"],
    tags: ["kseeb", "mysuru", "community"],
    status: "accepted",
    languageMedium: ["Kannada", "English"],
    transportAvailable: "yes",
  },
];

// --- Activities Data ---
export const activities = [
  { schoolId: schoolIds[0], activities: ['Leadership Development', 'Technology Integration', 'Cultural Education'] },
  { schoolId: schoolIds[1], activities: ['Focusing on Academics', 'STEM Activities', 'Empowering in Sports'] },
  { schoolId: schoolIds[2], activities: ['Focusing on Academics', 'Special Focus on Physical Education'] },
  { schoolId: schoolIds[3], activities: ['Empowering in Sports', 'Leadership Development'] },
  { schoolId: schoolIds[4], activities: ['Cultural Education', 'Technology Integration', 'Environmental Awareness'] },
  { schoolId: schoolIds[5], activities: ['Focuses on Practical Learning', 'Environmental Awareness'] },
  { schoolId: schoolIds[6], activities: ['STEM Activities', 'Focusing on Academics', 'Special Focus on Science'] },
  { schoolId: schoolIds[7], activities: ['Focuses on Theoretical Learning', 'Empowering in Arts'] },
  { schoolId: schoolIds[8], activities: ['Leadership Development', 'Environmental Awareness', 'Cultural Education'] },
  { schoolId: schoolIds[9], activities: ['Focusing on Academics', 'Special Focus on Science', 'Special Focus on Mathematics'] },
  { schoolId: schoolIds[10], activities: ['Empowering in Sports', 'Leadership Development'] },
  { schoolId: schoolIds[11], activities: ['Focusing on Academics', 'Cultural Education'] },
  { schoolId: schoolIds[12], activities: ['Cultural Education', 'Empowering in Arts', 'Environmental Awareness'] },
  { schoolId: schoolIds[13], activities: ['Focuses on Practical Learning', 'Focusing on Academics'] },
  { schoolId: schoolIds[14], activities: ['Focusing on Academics', 'Special Focus on Physical Education'] },
  { schoolId: schoolIds[15], activities: ['Empowering in Arts', 'Technology Integration'] },
  { schoolId: schoolIds[16], activities: ['Focusing on Academics', 'STEM Activities'] },
  { schoolId: schoolIds[17], activities: ['Special Focus on Science', 'Leadership Development'] },
  { schoolId: schoolIds[18], activities: ['Environmental Awareness', 'Empowering in Arts', 'Focuses on Practical Learning'] },
  { schoolId: schoolIds[19], activities: ['Cultural Education', 'Focusing on Academics'] },
  { schoolId: schoolIds[20], activities: ['Focusing on Academics', 'STEM Activities'] },
  { schoolId: schoolIds[21], activities: ['Empowering in Sports', 'Focuses on Practical Learning'] },
  { schoolId: schoolIds[22], activities: ['Technology Integration', 'Leadership Development'] },
  { schoolId: schoolIds[23], activities: ['Focuses on Theoretical Learning'] },
  { schoolId: schoolIds[24], activities: ['Cultural Education', 'Special Focus on Mathematics'] },
];

// --- Alumni Data ---
export const alumni = [
  { schoolId: schoolIds[0], topAlumnis: [{ name: 'Isha Ambani', percentage: 99.0 }], famousAlumnies: [{ name: 'Ananya Panday', profession: 'Actor' }] },
  { schoolId: schoolIds[1], topAlumnis: [{ name: 'Riya Mehta', percentage: 98.2 }], alumnis: [{ name: 'Arjun Desai', percentage: 95.5 }] },
  { schoolId: schoolIds[2], famousAlumnies: [{ name: 'Sunil Gavaskar', profession: 'Cricketer' }], topAlumnis: [{ name: 'John Fernandes', percentage: 97.1 }] },
  { schoolId: schoolIds[3], famousAlumnies: [{ name: 'Leander Paes', profession: 'Tennis Player' }], topAlumnis: [{ name: 'Vikram Singh', percentage: 96.8 }] },
  { schoolId: schoolIds[4], topAlumnis: [{ name: 'Aditi Rao', percentage: 98.5 }], alumnis: [{ name: 'Siddharth Jain', percentage: 94.0 }] },
  { schoolId: schoolIds[5], topAlumnis: [{ name: 'Pooja Patil', percentage: 92.5 }], alumnis: [] },
  { schoolId: schoolIds[6], topAlumnis: [{ name: 'Ankit Agarwal', percentage: 99.1 }], alumnis: [{ name: 'Neha Sharma', percentage: 97.2 }] },
  { schoolId: schoolIds[7], topAlumnis: [{ name: 'Sameer Joshi', percentage: 95.0 }], alumnis: [] },
  { schoolId: schoolIds[8], famousAlumnies: [{ name: 'Nikesh Arora', profession: 'CEO, Palo Alto Networks' }], topAlumnis: [{ name: 'Aarav Reddy', percentage: 98.8 }] },
  { schoolId: schoolIds[9], famousAlumnies: [{ name: 'Deepika Padukone', profession: 'Actor' }], topAlumnis: [{ name: 'Priya Kumar', percentage: 99.4 }] },
  { schoolId: schoolIds[10], famousAlumnies: [{ name: 'Rahul Dravid', profession: 'Cricketer' }], topAlumnis: [{ name: 'Rohan Matthew', percentage: 97.5 }] },
  { schoolId: schoolIds[11], topAlumnis: [{ name: 'Kavita Iyer', percentage: 96.0 }], alumnis: [] },
  { schoolId: schoolIds[12], topAlumnis: [{ name: 'Ganesh Murthy', percentage: 97.8 }], famousAlumnies: [{ name: 'Yash', profession: 'Actor' }] },
  { schoolId: schoolIds[13], topAlumnis: [{ name: 'Lakshmi Gowda', percentage: 94.2 }], alumnis: [] },
  { schoolId: schoolIds[14], topAlumnis: [{ name: 'Suresh Kamath', percentage: 95.5 }], alumnis: [] },
  { schoolId: schoolIds[15], topAlumnis: [{ name: 'Aisha Khan', percentage: 96.5 }], alumnis: [{ name: 'Rohan Kapoor', percentage: 93.1 }] },
  { schoolId: schoolIds[16], topAlumnis: [{ name: 'Shreya Gupta', percentage: 98.9 }], alumnis: [] },
  { schoolId: schoolIds[17], topAlumnis: [{ name: 'Rajesh Kumar', percentage: 97.0 }], famousAlumnies: [{ name: 'IAS Officer', profession: 'Civil Servant' }] },
  { schoolId: schoolIds[18], topAlumnis: [{ name: 'Anand Sharma', percentage: 95.0 }], alumnis: [] },
  { schoolId: schoolIds[19], topAlumnis: [{ name: 'Divya Shetty', percentage: 96.2 }], alumnis: [] },
  { schoolId: schoolIds[20], topAlumnis: [{ name: 'Karan Malhotra', percentage: 97.3 }], alumnis: [] },
  { schoolId: schoolIds[21], topAlumnis: [{ name: 'Naina Patel', percentage: 98.1 }], alumnis: [{ name: 'Vivek Singh', percentage: 95.8 }] },
  { schoolId: schoolIds[22], topAlumnis: [{ name: 'Zara Ahmed', percentage: 98.6 }], alumnis: [] },
  { schoolId: schoolIds[23], topAlumnis: [{ name: 'Sunil Jadhav', percentage: 85.0 }], alumnis: [] },
  { schoolId: schoolIds[24], topAlumnis: [{ name: 'Prakash Rao', percentage: 96.6 }], alumnis: [] },
];

// --- Amenities Data ---
export const amenities = [
  { schoolId: schoolIds[0], predefinedAmenities: ['Library', 'Science Lab', 'Swimming Pool', 'Auditorium', 'Smart Classes'], customAmenities: ['AI & Robotics Lab'] },
  { schoolId: schoolIds[1], predefinedAmenities: ['Library', 'Computer Lab', 'Playground', 'Transport'], customAmenities: ['Digital Library'] },
  { schoolId: schoolIds[2], predefinedAmenities: ['Library', 'Playground', 'Canteen'], customAmenities: [] },
  { schoolId: schoolIds[3], predefinedAmenities: ['Library', 'Playground', 'Swimming Pool', 'Sports Complex', 'Hostel'], customAmenities: ['Horse Riding Club'] },
  { schoolId: schoolIds[4], predefinedAmenities: ['Library', 'Science Lab', 'Auditorium', 'Smart Classes', 'Transport'], customAmenities: ['International Exchange Program'] },
  { schoolId: schoolIds[5], predefinedAmenities: ['Playground', 'Library'], customAmenities: [] },
  { schoolId: schoolIds[6], predefinedAmenities: ['Library', 'Science Lab', 'Computer Lab', 'Smart Classes', 'Transport'], customAmenities: ['Abacus Training'] },
  { schoolId: schoolIds[7], predefinedAmenities: ['Library', 'Playground', 'Art Room'], customAmenities: [] },
  { schoolId: schoolIds[8], predefinedAmenities: ['Library', 'Swimming Pool', 'Hostel', 'Sports Complex', 'Smart Classes'], customAmenities: ['Equestrian Center'] },
  { schoolId: schoolIds[9], predefinedAmenities: ['Library', 'Science Lab', 'Computer Lab', 'Auditorium'], customAmenities: ['Advanced Science Labs'] },
  { schoolId: schoolIds[10], predefinedAmenities: ['Library', 'Playground', 'Hostel', 'Sports Complex'], customAmenities: ['Cricket Ground (International Standard)'] },
  { schoolId: schoolIds[11], predefinedAmenities: ['Library', 'Playground', 'Computer Lab'], customAmenities: [] },
  { schoolId: schoolIds[12], predefinedAmenities: ['Library', 'Transport', 'Art Room', 'Playground'], customAmenities: ['Yoga and Meditation Hall'] },
  { schoolId: schoolIds[13], predefinedAmenities: ['Library', 'Playground'], customAmenities: [] },
  { schoolId: schoolIds[14], predefinedAmenities: ['Library', 'Science Lab', 'Playground'], customAmenities: ['Chapel'] },
  { schoolId: schoolIds[15], predefinedAmenities: ['Library', 'Smart Classes', 'Transport', 'Music Room'], customAmenities: ['Performing Arts Studio'] },
  { schoolId: schoolIds[16], predefinedAmenities: ['Library', 'Science Lab', 'Computer Lab', 'Transport', 'Playground'], customAmenities: [] },
  { schoolId: schoolIds[17], predefinedAmenities: ['Library', 'Hostel', 'Playground', 'Science Lab'], customAmenities: [] },
  { schoolId: schoolIds[18], predefinedAmenities: ['Library', 'Art Room', 'Amphitheater'], customAmenities: ['Nature Trail'] },
  { schoolId: schoolIds[19], predefinedAmenities: ['Library', 'Transport', 'Playground', 'Hostel'], customAmenities: [] },
  { schoolId: schoolIds[20], predefinedAmenities: ['Library', 'Science Lab', 'Computer Lab', 'Playground'], customAmenities: ['In-house Cafeteria'] },
  { schoolId: schoolIds[21], predefinedAmenities: ['Library', 'Swimming Pool', 'Smart Classes', 'Transport'], customAmenities: ['Skating Rink'] },
  { schoolId: schoolIds[22], predefinedAmenities: ['Library', 'Science Lab', 'Swimming Pool', 'Hostel', 'Transport'], customAmenities: ['Golf Course access'] },
  { schoolId: schoolIds[23], predefinedAmenities: ['Library'], customAmenities: ['Skill Development Workshops'] },
  { schoolId: schoolIds[24], predefinedAmenities: ['Library', 'Transport', 'Playground', 'Art Room'], customAmenities: ['Kannada Cultural Center'] },
];